name: solarcycle25

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - astropy=5.1
  - h5py==3.1.0
  - httplib2==0.19.0
  - jupyterlab=3.3.2
  - matplotlib=3.3.4
  - numpy=1.20.1
  - pandas=1.2.3
  - packaging=21.3
  - pip=21.1
  - pyhdf==0.10.2
  - scipy=1.6.0
  - urllib3=1.26.8
  
